name: barmo
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0-71.0.dev

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  mobile_scanner: ^6.0.2
  qr_flutter: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - images/perfil.jpg
    - images/bebidas.jpg
    - images/alitas.jpg
    - images/snacks.jpg
    - images/bg.jpeg
    - images/Cervezas.png
    - icons/icons8-mesa-de-restaurante-64.png
    - assets/productos.json