name: barmo
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0-71.0.dev

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  mobile_scanner: ^6.0.2
  mongo_dart: ^0.10.3
  qr_flutter: ^4.1.0
  sqflite: ^2.0.0+4
  path_provider: ^2.0.11
  cached_network_image: ^3.2.1
  shared_preferences: ^2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/perfil.jpg
    - assets/images/bebidas.jpg
    - assets/images/alitas.jpg
    - assets/images/snacks.jpg
    - assets/images/bg.jpeg
    - assets/images/Cervezas.png
    - assets/icons/icons8-mesa-de-restaurante-64.png